#sudo: required

os : linux

language: generic

services: 
  - docker

before_install:
  - docker build -t jeong5680/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jeong5680/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"